/**
 * This file was generated by the Jeddict
 */ 

package br.com.everton.sumula.model;

import br.com.everton.sumula.model.type.Estado;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import javax.persistence.*;

/**
 * @author everton
 */

@Entity
public class Estadio { 

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    @Basic
    private String nome;

    @Basic
    private String cidade;

    @Enumerated(EnumType.STRING)
    private Estado estado;

    protected Estadio() {
        // construtor vazio para serialização
    }

    public Long getId() {
        return id;
    }

    public String getNome() {
        return this.nome;
    }

    public String getCidade() {
        return this.cidade;
    }

    public Estado getEstado() {
        return this.estado;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        Estadio estadio = (Estadio) o;

        return new EqualsBuilder()
                .append(id, estadio.id)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
                .append(id)
                .toHashCode();
    }
}
