/**
 * This file was generated by the Jeddict
 */
package br.com.tdc.sumula.tradicional.model;

import br.com.tdc.sumula.tradicional.type.TempoDeJogo;
import br.com.tdc.sumula.tradicional.type.TipoCartao;

import javax.persistence.Basic;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author everton
 */
@Entity
public class Cartao {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    @Enumerated(EnumType.STRING)
    private TipoCartao tipo;

    @Basic
    private String motivo;

    @Embedded
    private TempoDeJogo tempo;

    @ManyToOne(targetEntity = Relacionado.class)
    private Relacionado relacionado;

    private Cartao(Builder builder) {
        setTipo(builder.tipo);
        setMotivo(builder.motivo);
        setTempo(builder.tempo);
        setRelacionado(builder.relacionado);
    }

    public static Builder newBuilder() {
        return new Builder();
    }


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public TipoCartao getTipo() {
        return this.tipo;
    }

    public void setTipo(TipoCartao tipo) {
        this.tipo = tipo;
    }

    public String getMotivo() {
        return this.motivo;
    }

    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    public TempoDeJogo getTempo() {
        return this.tempo;
    }

    public void setTempo(TempoDeJogo tempo) {
        this.tempo = tempo;
    }

    public Relacionado getRelacionado() {
        return this.relacionado;
    }

    public void setRelacionado(Relacionado relacionado) {
        this.relacionado = relacionado;
    }

    public boolean isAmarelo() {
        return TipoCartao.AMARELO.equals(this.tipo);
    }

    public boolean isVermelho() {
        return TipoCartao.VERMELHO.equals(this.tipo);
    }

    public static final class Builder {
        private TipoCartao tipo;
        private String motivo;
        private TempoDeJogo tempo;
        private Relacionado relacionado;

        private Builder() {
        }

        public Builder withTipo(TipoCartao val) {
            tipo = val;
            return this;
        }

        public Builder withMotivo(String val) {
            motivo = val;
            return this;
        }

        public Builder withTempo(TempoDeJogo val) {
            tempo = val;
            return this;
        }

        public Builder withRelacionado(Relacionado val) {
            relacionado = val;
            return this;
        }

        public Cartao build() {
            return new Cartao(this);
        }
    }
}
