/**
 * This file was generated by the Jeddict
 */ 

package br.com.tdc.sumula.tradicional.model;

import br.com.tdc.sumula.tradicional.type.Estado;
import org.apache.commons.lang3.Validate;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import javax.persistence.*;

/**
 * @author everton
 */

@Entity
public class Estadio { 

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    @Basic
    private String descricao;

    @Basic
    private String cidade;

    @Enumerated(EnumType.STRING)
    private Estado estado;

    public Estadio(String descricao, String cidade, Estado estado) {
        this.descricao = Validate.notEmpty(descricao);
        this.cidade = Validate.notEmpty(cidade);
        this.estado = Validate.notNull(estado);
    }

    public Long getId() {
        return id;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public String getCidade() {
        return this.cidade;
    }

    public Estado getEstado() {
        return this.estado;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        Estadio estadio = (Estadio) o;

        return new EqualsBuilder()
                .append(id, estadio.id)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
                .append(id)
                .toHashCode();
    }
}
