/**
 * This file was generated by the Jeddict
 */ 

package br.com.tdc.sumula.tradicional.model;

import br.com.tdc.sumula.tradicional.type.TipoJogador;

import javax.persistence.*;
import java.io.Serializable;

/**
 * @author everton
 */

@Entity
public class Jogador implements Serializable {

    @Id
    private Long cbf;

    @Basic
    private String nome;

    @ManyToOne
    @JoinColumn(name = "id_time")
    private Time time;

    @Basic
    private String apelido;

    @Enumerated(EnumType.STRING)
    private TipoJogador tipo;

    private Jogador(Builder builder) {
        setCbf(builder.cbf);
        nome = builder.nome;
        setTime(builder.time);
        apelido = builder.apelido;
        tipo = builder.tipo;
    }

    protected Jogador() {
        // Construtor vazio para serialização
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public Long getCbf() {
        return this.cbf;
    }

    public void setCbf(Long cbf) {
        this.cbf = cbf;
    }

    public Time getTime() {
        return time;
    }

    public void setTime(Time time) {
        this.time = time;
    }

    public String getNome() {
        return this.nome;
    }


    public String getApelido() {
        return this.apelido;
    }


    public TipoJogador getTipo() {
        return this.tipo;
    }


    public static final class Builder {
        private Long cbf;
        private String nome;
        private Time time;
        private String apelido;
        private TipoJogador tipo;

        private Builder() {
        }

        public Builder withCbf(Long val) {
            cbf = val;
            return this;
        }

        public Builder withNome(String val) {
            nome = val;
            return this;
        }

        public Builder withTime(Time val) {
            time = val;
            return this;
        }

        public Builder withApelido(String val) {
            apelido = val;
            return this;
        }

        public Builder withTipo(TipoJogador val) {
            tipo = val;
            return this;
        }

        public Jogador build() {
            return new Jogador(this);
        }
    }
}
