/**
 * This file was generated by the Jeddict
 */ 

package br.com.everton.sumula.model.sumula;

import br.com.everton.sumula.model.type.TempoDeJogo;
import br.com.everton.sumula.model.Time;

import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author everton
 */

@Entity
public class Substituicao { 

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    @Embedded
    private TempoDeJogo tempo;

    @ManyToOne(targetEntity = Time.class)
    private Time time;

    @ManyToOne(targetEntity = Relacionado.class)
    private Relacionado saiu;

    @ManyToOne(targetEntity = Relacionado.class)
    private Relacionado entrou;

    public Substituicao(TempoDeJogo tempo, Relacionado saiu, Relacionado entrou) {
        this.tempo = tempo;
        this.time = saiu.getTime();
        this.saiu = saiu;
        this.entrou = entrou;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    public TempoDeJogo getTempo() {
        return this.tempo;
    }

    public void setTempo(TempoDeJogo tempo) {
        this.tempo = tempo;
    }


    public Time getTime() {
        return this.time;
    }

    public void setTime(Time time) {
        this.time = time;
    }


    public Relacionado getSaiu() {
        return this.saiu;
    }

    public void setSaiu(Relacionado saiu) {
        this.saiu = saiu;
    }


    public Relacionado getEntrou() {
        return this.entrou;
    }

    public void setEntrou(Relacionado entrou) {
        this.entrou = entrou;
    }


}
